### PR TITLE
Move grader source into src/

### PR DESCRIPTION
**Pull request by michaelwisely**
For @brhoades :3

This is mostly a joke, although it seems to work.

### CODE REVIEW

**Comment by brhoades** [comment]
Please consider moving into /grader/grader/grader/grader/src

**Comment by brhoades** [comment]
I'd actually like to see this done before we add 20 more things and have to resolve further conflicts. @LinuxMercedes opinions?

**Comment by LinuxMercedes** [comment]
Wait, this wasn't a joke PR?

**Comment by brhoades** [comment]
If it's a joke, it's not very funny. grader/grader/grader is a ridiculous structure :).

**Comment by LinuxMercedes** [comment]
@michaelwisely @brhoades if y'all actually want this, someone should fix the conflicts and merge this PR right quick!

**Comment by michaelwisely** [comment]
I can have a look this weekend. The PR currently breaks something.... I
don't remember what.

**Comment by LinuxMercedes** [comment]
On second thought let's not do this; `setup.py` / `pip` packaging kind of expect packages to live in a directory named after themselves.

**Pull request closed without merging**
