### PR TITLE
grader remove - Student Submission Container Removal

### PR DESCRIPTION
**Pull request by brhoades**
For #1--- this allows the removal of submission containers per assignment and optionally per set of students.

Blanket removal:
```bash
   $ grader remove hw1
   INFO     Containers to delete:
   INFO       bjrq48 (1 container(s)):
   INFO         1661d79d7a88cd6c47268bbc45fcd021d45b450276261b3fa3b19cf83580e73f created on 2017-02-25 21:01:58
   INFO       nmjxc9 (1 container(s)):
   INFO         5a75dc16334a393d9ac6cc70980c7a53599aa73db2f8766affa290151748116b created on 2017-02-25 21:02:01
   INFO       mwcp2 (1 container(s)):
   INFO         ba4e4a891f69023359d312149629f05cf1f36a63694cb77a31c3f23514974469 created on 2017-02-25 21:02:06
   Are you sure you wish to remove the containers listed above [yes/no] (no): yes
   INFO     Removing container 1661d79d7a88cd6c47268bbc45fcd021d45b450276261b3fa3b19cf83580e73f
   INFO     Removing container 5a75dc16334a393d9ac6cc70980c7a53599aa73db2f8766affa290151748116b
   INFO     Removing container ba4e4a891f69023359d312149629f05cf1f36a63694cb77a31c3f23514974469
```

Specific users (you could list any number of users).
```bash
   $ grader remove hw1 bjrq48
   INFO     Containers to delete:
   INFO       bjrq48 (1 container(s)):
   INFO         1661d79d7a88cd6c47268bbc45fcd021d45b450276261b3fa3b19cf83580e73f created on 2017-02-25 21:01:58
   Are you sure you wish to remove the containers listed above [yes/no] (no): yes
   INFO     Removing container 1661d79d7a88cd6c47268bbc45fcd021d45b450276261b3fa3b19cf83580e73f
```

Exclude listed users' containers (negate the query).
```bash
   $ grader remove --exclude-listed hw1 bjrq48
   INFO     Containers to delete:
   INFO       nmjxc9 (1 container(s)):
   INFO         5a75dc16334a393d9ac6cc70980c7a53599aa73db2f8766affa290151748116b created on 2017-02-25 21:02:01
   INFO       mwcp2 (1 container(s)):
   INFO         ba4e4a891f69023359d312149629f05cf1f36a63694cb77a31c3f23514974469 created on 2017-02-25 21:02:06
   Are you sure you wish to remove the containers listed above [yes/no] (no): yes
   INFO     Removing container 5a75dc16334a393d9ac6cc70980c7a53599aa73db2f8766affa290151748116b
   INFO     Removing container ba4e4a891f69023359d312149629f05cf1f36a63694cb77a31c3f23514974469

### CODE REVIEW

**Comment by LinuxMercedes** [comment]
What do you think about just calling it `--exclude`?

Also, to clarify: this just junks the containers, not the submissions themselves, right?

**Comment by brhoades** [comment]
Right @LinuxMercedes. There was a lot of scope limiting here--- the initial issue regarded removal of just containers, so that's what this in. In the future, there should likely be some commands (or arguments) for cleaning old submissions / images.

Regarding `--exclude`: I'd agree with you if `--exclude` took a list of users. However, seeing as it simply flips the query, I feel it's better if it's explicit? I'd be interested for any ideas on changing this though.

**Comment by michaelwisely** [comment]
Would it make sense to have a separate command to delete submissions?
Similar to the way docker has `docker rm` and `docker rmi`.

On Feb 26, 2017 12:39 PM, "Billy Rhoades" <notifications@github.com> wrote:

Right @LinuxMercedes <https://github.com/LinuxMercedes>. There was a lot of
scope limiting here--- the initial issue regarded removal of just
containers, so that's what this in. In the future, there should likely be
some commands (or arguments) for cleaning old submissions / images.

Regarding --exclude: I'd agree with you if --exclude took a list of users.
However, seeing as it simply flips the query, I feel it's better if it's
explicit? I'd be interested for any ideas on changing this though.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/redkyn/grader/pull/32#issuecomment-282576764>, or mute
the thread

**Comment by LinuxMercedes** [comment]
I'm not sure what the use case for removing submissions would be...usually that's something you wouldn't want to lose. I guess you could remove assignments for students that drop?

**Comment by michaelwisely** [comment]
@LinuxMercedes or if you accidentally import something incorrectly

**Comment by brhoades** [comment]
Before I put time into this, we discussed making remove a package within commands/. We could then define subcommands for various removal tasks (ie submissions here).

Can I get a :+1: before I start this?

**Comment by brhoades** [comment]
Closing for refactor.

**Pull request closed without merging**
